version: "3.7"

services:
  postgres:
    image: postgres
    platform: linux/amd64
    expose:
      - "5433"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shared

  web-api:
    image: codechallenge/web-api:latest
    platform: linux/amd64
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
      args:
        name: "web-api"
    ports:
      - 3001:3001
    depends_on:
      - postgres
    environment:
      - ENV=local