version: "3.7"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_code_challenges
    expose:
      - "5436"
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./migrations/sql:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - 3001:3001
    depends_on:
      - postgres
    volumes:
      - ./:/app/main
